version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/home/circleci/project/:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - "4444"
    command: ["-limit", "4", "-conf", "/etc/selenoid/browsers.json"]
