version: 2.1
orbs:
  allure: ayte/allure@0.1.3
  openjdk-install: cloudesire/openjdk-install@1.2.3
jobs:
  main:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - allure/install
      - run:
          name: "Check python version"
          command: "python --version"
      - run:
          name: "Install the requirements"
          command: "chmod +x scripts/install.sh; bash -v ./scripts/install.sh"
      - run:
          name: "Run the tests"
          command: "chmod +x scripts/run.sh; bash -v ./scripts/run.sh"
      - run:
          name: "Generate the test report"
          command: "chmod +x scripts/report.sh; bash -v ./scripts/report.sh"
          when: always
      - store_test_results:
          path: /home/circleci/project/allure-report
      - store_test_results:
          path: /home/circleci/project/results_ui.xml
workflows:
  aqa-engineer-test-task:
    jobs:
      - main
