version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: host
    ports:
      - "4444:4444"
    volumes:
      - "./:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/video:/opt/selenoid/video"
      - "/etc/logs:/opt/selenoid/logs"
    expose:
      - "4444"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/etc/video
      - HOST="0.0.0.0"
    command: ["-limit", "4", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
